/* 
 * OnBoarding
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = IO.Swagger.Client.SwaggerDateConverter;
namespace IO.Swagger.Model
{
    /// <summary>
    /// Defines DocumentType
    /// </summary>
    [JsonConverter(typeof(StringEnumConverter))]
        public enum DocumentType
    {
        /// <summary>
        /// Enum IdentityCard for value: IdentityCard
        /// </summary>
        [EnumMember(Value = "IdentityCard")]
        IdentityCard = 1,
        /// <summary>
        /// Enum DrivingLicense for value: DrivingLicense
        /// </summary>
        [EnumMember(Value = "DrivingLicense")]
        DrivingLicense = 2,
        /// <summary>
        /// Enum Passport for value: Passport
        /// </summary>
        [EnumMember(Value = "Passport")]
        Passport = 3    }
}
