/* 
 * OnBoarding
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = IO.Swagger.Client.SwaggerDateConverter;
namespace IO.Swagger.Model
{
    /// <summary>
    /// Defines ExceptionCodeEnum
    /// </summary>
    [JsonConverter(typeof(StringEnumConverter))]
        public enum ExceptionCodeEnum
    {
        /// <summary>
        /// Enum E000 for value: E000
        /// </summary>
        [EnumMember(Value = "E000")]
        E000 = 1,
        /// <summary>
        /// Enum E001 for value: E001
        /// </summary>
        [EnumMember(Value = "E001")]
        E001 = 2,
        /// <summary>
        /// Enum E002 for value: E002
        /// </summary>
        [EnumMember(Value = "E002")]
        E002 = 3,
        /// <summary>
        /// Enum E003 for value: E003
        /// </summary>
        [EnumMember(Value = "E003")]
        E003 = 4,
        /// <summary>
        /// Enum E004 for value: E004
        /// </summary>
        [EnumMember(Value = "E004")]
        E004 = 5,
        /// <summary>
        /// Enum E005 for value: E005
        /// </summary>
        [EnumMember(Value = "E005")]
        E005 = 6,
        /// <summary>
        /// Enum E006 for value: E006
        /// </summary>
        [EnumMember(Value = "E006")]
        E006 = 7,
        /// <summary>
        /// Enum E007 for value: E007
        /// </summary>
        [EnumMember(Value = "E007")]
        E007 = 8,
        /// <summary>
        /// Enum E008 for value: E008
        /// </summary>
        [EnumMember(Value = "E008")]
        E008 = 9,
        /// <summary>
        /// Enum E009 for value: E009
        /// </summary>
        [EnumMember(Value = "E009")]
        E009 = 10,
        /// <summary>
        /// Enum E010 for value: E010
        /// </summary>
        [EnumMember(Value = "E010")]
        E010 = 11,
        /// <summary>
        /// Enum E011 for value: E011
        /// </summary>
        [EnumMember(Value = "E011")]
        E011 = 12,
        /// <summary>
        /// Enum E012 for value: E012
        /// </summary>
        [EnumMember(Value = "E012")]
        E012 = 13,
        /// <summary>
        /// Enum E013 for value: E013
        /// </summary>
        [EnumMember(Value = "E013")]
        E013 = 14,
        /// <summary>
        /// Enum E014 for value: E014
        /// </summary>
        [EnumMember(Value = "E014")]
        E014 = 15,
        /// <summary>
        /// Enum E015 for value: E015
        /// </summary>
        [EnumMember(Value = "E015")]
        E015 = 16,
        /// <summary>
        /// Enum E016 for value: E016
        /// </summary>
        [EnumMember(Value = "E016")]
        E016 = 17,
        /// <summary>
        /// Enum E017 for value: E017
        /// </summary>
        [EnumMember(Value = "E017")]
        E017 = 18,
        /// <summary>
        /// Enum E018 for value: E018
        /// </summary>
        [EnumMember(Value = "E018")]
        E018 = 19,
        /// <summary>
        /// Enum E019 for value: E019
        /// </summary>
        [EnumMember(Value = "E019")]
        E019 = 20,
        /// <summary>
        /// Enum E020 for value: E020
        /// </summary>
        [EnumMember(Value = "E020")]
        E020 = 21,
        /// <summary>
        /// Enum E021 for value: E021
        /// </summary>
        [EnumMember(Value = "E021")]
        E021 = 22,
        /// <summary>
        /// Enum E022 for value: E022
        /// </summary>
        [EnumMember(Value = "E022")]
        E022 = 23,
        /// <summary>
        /// Enum E023 for value: E023
        /// </summary>
        [EnumMember(Value = "E023")]
        E023 = 24,
        /// <summary>
        /// Enum E024 for value: E024
        /// </summary>
        [EnumMember(Value = "E024")]
        E024 = 25,
        /// <summary>
        /// Enum E025 for value: E025
        /// </summary>
        [EnumMember(Value = "E025")]
        E025 = 26,
        /// <summary>
        /// Enum E026 for value: E026
        /// </summary>
        [EnumMember(Value = "E026")]
        E026 = 27,
        /// <summary>
        /// Enum E999 for value: E999
        /// </summary>
        [EnumMember(Value = "E999")]
        E999 = 28    }
}
