/* 
 * OnBoarding
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = IO.Swagger.Client.SwaggerDateConverter;
namespace IO.Swagger.Model
{
    /// <summary>
    /// GetAllSessionResponse
    /// </summary>
    [DataContract]
        public partial class GetAllSessionResponse :  IEquatable<GetAllSessionResponse>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="GetAllSessionResponse" /> class.
        /// </summary>
        /// <param name="sessions">sessions.</param>
        /// <param name="totalSession">totalSession.</param>
        public GetAllSessionResponse(List<GetSessionResponse> sessions = default(List<GetSessionResponse>), int? totalSession = default(int?))
        {
            this.Sessions = sessions;
            this.TotalSession = totalSession;
        }
        
        /// <summary>
        /// Gets or Sets Sessions
        /// </summary>
        [DataMember(Name="sessions", EmitDefaultValue=false)]
        public List<GetSessionResponse> Sessions { get; set; }

        /// <summary>
        /// Gets or Sets TotalSession
        /// </summary>
        [DataMember(Name="totalSession", EmitDefaultValue=false)]
        public int? TotalSession { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class GetAllSessionResponse {\n");
            sb.Append("  Sessions: ").Append(Sessions).Append("\n");
            sb.Append("  TotalSession: ").Append(TotalSession).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as GetAllSessionResponse);
        }

        /// <summary>
        /// Returns true if GetAllSessionResponse instances are equal
        /// </summary>
        /// <param name="input">Instance of GetAllSessionResponse to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(GetAllSessionResponse input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.Sessions == input.Sessions ||
                    this.Sessions != null &&
                    input.Sessions != null &&
                    this.Sessions.SequenceEqual(input.Sessions)
                ) && 
                (
                    this.TotalSession == input.TotalSession ||
                    (this.TotalSession != null &&
                    this.TotalSession.Equals(input.TotalSession))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Sessions != null)
                    hashCode = hashCode * 59 + this.Sessions.GetHashCode();
                if (this.TotalSession != null)
                    hashCode = hashCode * 59 + this.TotalSession.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }
}
