/* 
 * OnBoarding
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = IO.Swagger.Client.SwaggerDateConverter;
namespace IO.Swagger.Model
{
    /// <summary>
    /// GetAcquiredUserInfo
    /// </summary>
    [DataContract]
        public partial class GetAcquiredUserInfo :  IEquatable<GetAcquiredUserInfo>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="GetAcquiredUserInfo" /> class.
        /// </summary>
        /// <param name="personalData">personalData.</param>
        /// <param name="idCard">idCard.</param>
        public GetAcquiredUserInfo(PersonalDataAcquiredUserInfoResponse personalData = default(PersonalDataAcquiredUserInfoResponse), IDCardAcquiredUserResponse idCard = default(IDCardAcquiredUserResponse))
        {
            this.PersonalData = personalData;
            this.IdCard = idCard;
        }
        
        /// <summary>
        /// Gets or Sets PersonalData
        /// </summary>
        [DataMember(Name="personalData", EmitDefaultValue=false)]
        public PersonalDataAcquiredUserInfoResponse PersonalData { get; set; }

        /// <summary>
        /// Gets or Sets IdCard
        /// </summary>
        [DataMember(Name="idCard", EmitDefaultValue=false)]
        public IDCardAcquiredUserResponse IdCard { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class GetAcquiredUserInfo {\n");
            sb.Append("  PersonalData: ").Append(PersonalData).Append("\n");
            sb.Append("  IdCard: ").Append(IdCard).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as GetAcquiredUserInfo);
        }

        /// <summary>
        /// Returns true if GetAcquiredUserInfo instances are equal
        /// </summary>
        /// <param name="input">Instance of GetAcquiredUserInfo to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(GetAcquiredUserInfo input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.PersonalData == input.PersonalData ||
                    (this.PersonalData != null &&
                    this.PersonalData.Equals(input.PersonalData))
                ) && 
                (
                    this.IdCard == input.IdCard ||
                    (this.IdCard != null &&
                    this.IdCard.Equals(input.IdCard))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.PersonalData != null)
                    hashCode = hashCode * 59 + this.PersonalData.GetHashCode();
                if (this.IdCard != null)
                    hashCode = hashCode * 59 + this.IdCard.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }
}
