/* 
 * OnBoarding
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = IO.Swagger.Client.SwaggerDateConverter;
namespace IO.Swagger.Model
{
    /// <summary>
    /// Defines SessionFlowTypeDto
    /// </summary>
    [JsonConverter(typeof(StringEnumConverter))]
        public enum SessionFlowTypeDto
    {
        /// <summary>
        /// Enum Dynamic for value: Dynamic
        /// </summary>
        [EnumMember(Value = "Dynamic")]
        Dynamic = 1,
        /// <summary>
        /// Enum Ai for value: Ai
        /// </summary>
        [EnumMember(Value = "Ai")]
        Ai = 2,
        /// <summary>
        /// Enum Spid for value: Spid
        /// </summary>
        [EnumMember(Value = "Spid")]
        Spid = 3,
        /// <summary>
        /// Enum Cie for value: Cie
        /// </summary>
        [EnumMember(Value = "Cie")]
        Cie = 4    }
}
