/* 
 * OnBoarding
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = IO.Swagger.Client.SwaggerDateConverter;
namespace IO.Swagger.Model
{
    /// <summary>
    /// Defines Sex
    /// </summary>
    [JsonConverter(typeof(StringEnumConverter))]
        public enum Sex
    {
        /// <summary>
        /// Enum NotKnown for value: NotKnown
        /// </summary>
        [EnumMember(Value = "NotKnown")]
        NotKnown = 1,
        /// <summary>
        /// Enum Male for value: Male
        /// </summary>
        [EnumMember(Value = "Male")]
        Male = 2,
        /// <summary>
        /// Enum Female for value: Female
        /// </summary>
        [EnumMember(Value = "Female")]
        Female = 3,
        /// <summary>
        /// Enum NotApplicable for value: NotApplicable
        /// </summary>
        [EnumMember(Value = "NotApplicable")]
        NotApplicable = 4    }
}
